name: Build app
description: Build & Lint app

runs:
 using: 'composite'
 steps:
    - name: Lint code
        run: npm run lint

    - name: Build app
        run: npm run build
        env:
          VITE_ENVIRONMENT: ${{ env.VITE_VERCEL_ENV }}
